version: '3.8'

services:
  #  1. Backend (API Python) 
  backend:
    build: ./backend
    container_name: aeroflash-backend
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - app-network

  # 2. Frontend (Nginx) 
  frontend:
    build: ./frontend
    container_name: aeroflash-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  #  3. Monitoreo de Métricas (Prometheus) 
  prometheus:
    image: prom/prometheus:latest
    container_name: aeroflash-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  #  4. Visualización (Grafana) 
  grafana:
    image: grafana/grafana:latest
    container_name: aeroflash-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

  #  5. Jenkins (CI/CD) 
  jenkins:
    build: ./jenkins
    container_name: aeroflash-jenkins
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/app:/home/ubuntu/app
    networks:
      - app-network

  #  6. Logging Centralizado (Loki) 
  loki:
    image: grafana/loki:2.9.0
    container_name: aeroflash-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  #  7. Recolector de Logs (Promtail) 
  promtail:
    image: grafana/promtail:2.9.0
    container_name: aeroflash-promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network

  #  8. Calidad de Código (SonarQube) 
  sonarqube:
    image: sonarqube:community
    container_name: aeroflash-sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

