global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:5000'] # Nombre del servicio en docker-compose
